version: '3'

services:
  jenkins:
    container_name: jenkins
    image: docker.io/bitnami/jenkins:2
    restart: always
    ports:
      - '18085:8080'
    environment:
      - TZ=Asia/Seoul
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

networks:
  default:
    external: true
    name: dev-net

volumes:
  jenkins_data:
    driver: local
