version: '3'

services:
  grafana:
    container_name: grafana
    image: docker.io/bitnami/grafana:8
    restart: always
    ports:
      - '3000:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=bitnami'
      - TZ: 'Asia/Seoul'
    volumes:
      - grafana_data:/opt/bitnami/grafana/data
      
networks:
  default:
    external: true
    name: dev-net

volumes:
  grafana_data:
    driver: local
