version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Seoul
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.1
    restart: always
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Seoul
    depends_on:
      - zookeeper
      
networks:
  default:
    external: true
    name: dev-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
