version: '3'

services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - TZ=Asia/Seoul
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
    container_name: redmine
    image: docker.io/bitnami/redmine:4
    restart: always
    ports:
      - '18081:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - TZ=Asia/Seoul
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine

networks:
  default:
    external: true
    name: dev-net

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
